apiVersion: v1
kind: Secret
metadata:
  name: noah-backend-secret
  namespace: noah-dev
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: "2gimlLf80t1WTCewdBnSjz_BQdxkfYdGTWD792PjgIZ4UGYxTEwRZpsXtO88XmgQDAc"

  # Postgres
  POSTGRES_PASSWORD: "PhBGasZSfCYQ6h-lxY7bzHSOHN2eVKzfJCprj1TbCsA"
  
  
